apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-test
  namespace: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool1
  template:
    metadata:
      labels:
        app: multitool1
    spec:
      containers:
        - image: wbitt/network-multitool
          name: multitool1
          ports:
          - containerPort: 80

