apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: App of Apps

  # Allow apps to only deploy from our github org so we can set up for review
  sourceRepos:
  - 'https://github.com/rajcsingh-git/*'

  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: 'Application'