apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-managed-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra-apps
    repoURL: https://github.com/rajcsingh-git/my-app-of-apps.git
    targetRevision: main
  syncPolicy:
    automated: 
      selfHeal: true
