apiVersion: argoproj.io/v1alpha1 
kind: AppProject 
metadata: 
  name: infra-proj 
  namespace: argocd 
# Finalizer that ensures that project is not deleted until it is not referenced by any application 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  description: CPA Infra Apps 

  # Allow manifests to deploy from any Git repos 
  sourceRepos: 
   - '*' 

  destinations:   
   - namespace: nginx-ingress 
     server: '*' 
   - namespace: nginx 
     server: '*' 
   - namespace: argocd 
     server: '*' 
   - namespace: cluster-monitoring
     server: '*'
   - namespace: multitool
     server: '*'
   - namespace: kube-prometheus
     server: '*'
 
  clusterResourceWhitelist: 
    - group: '*' 
      kind: '*' 
