apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-app-test-clusters
  namespace: argocd
spec:
  generators:
    - list: 
        elements:
        - cluster: in-cluster
          url: https://kubernetes.default.svc
#        - cluster: kubernetes-admin-cka01@kubernetes
#          url: https://192.168.100.223:6443
#        - cluster: kubernetes-admin-cka02@kubernetes
#          url: https://192.168.100.166:6443

  template:
    metadata:
      name: '{{cluster}}-multitool'
      namespace: gh-weekly-test
    spec:
      project: infra-proj
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: https://github.com/rajcsingh-git/my-app-of-apps.git
        targetRevision: main
        path: multitool-test
      destination:
        server: '{{url}}'
        namespace: multitool
