apiVersion: argoproj.io/v1alpha
kind: ApplicationSet
metadata:
  name: githb-weekly-across-clusters
  namespace: argocd
spec:
  generators:
    - list: 
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
      - cluster: kubernetes-admin-cka01@kubernetes
        url: https://192.168.100.223:6443
      - cluster: kubernetes-admin-cka02@kubernetes
        url: https://192.168.100.166:6443

  template:
    metadata:
      name: '{{cluster}}-nginx'
      namespace: gh-weekly-test
    spec:
      project: infra-proj
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/headllines/github-weekly
        #repoURL: https://github.com/christianh814/gitops-examples
        targetRevision: master
        #path: applicationsets/list-generator/overlays/{{cluster}}
        path: /
      destination:
        server: '{{url}}'
        namespace: gh-weekly-test
